# Generated by Django 5.1.7 on 2025-03-31 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_title_alter_like_post_alter_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
